Repository kubernetes-csi/csi-driver-iscsi, pull requests merged in 2021-05, with the labels that each got.

#51 Rename iscsi_lib to iscsiLib to avoid snake case import
  pkg/iscsi/iscsi.go
  pkg/iscsi/iscsi_util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#47 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#54 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#55 master: update release-tools + OWNERS
  OWNERS
  OWNERS_ALIASES
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/OWNERS
  release-tools/OWNERS_ALIASES
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#56 correct csc execution section
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
