Repository kubernetes-csi/csi-driver-iscsi, pull requests merged in 2021-12, with the labels that each got.

#74 chore: add image local build
  .github/workflows/trivy.yaml
  .github/workflows/windows.yaml
  Makefile
  examples/nginx.yaml
  examples/pv.yaml
  examples/pvc.yaml
  examples/storageclass.yaml
  hack/verify-yamllint.sh
  kubernetes/csi-attacher-iscsiplugin.yaml
  kubernetes/csi-attacher-rbac.yaml
  kubernetes/csi-nodeplugin-iscsiplugin.yaml
  kubernetes/csi-nodeplugin-rbac.yaml
Labels: kind/feature, lgtm, size/L, release-note-none, cncf-cla: yes, approved

#75 address error return and unwanted type conversion
  pkg/iscsi/controllerserver.go
  pkg/iscsi/iscsi.go
  pkg/iscsi/iscsi_util.go
  pkg/iscsi/server.go
Labels: size/S, lgtm, release-note-none, cncf-cla: yes, approved

#78 Adjust the tag in deployment of node plugin yaml
  deploy/csi-iscsi-node.yaml
  examples/pod.yaml
Labels: size/XS, lgtm, release-note-none, cncf-cla: yes, approved

#79 Add details about the debugging of the driver
  docs/csi-debug.md
Labels: size/M, lgtm, release-note-none, cncf-cla: yes, approved

#80 test: add api version verification
  .github/workflows/pluto.yaml
Labels: kind/cleanup, size/S, lgtm, release-note-none, cncf-cla: yes, approved

#81 doc: update plugin version in the readme
  README.md
  SECURITY_CONTACTS
  pkg/iscsi/driver.go
Labels: size/S, lgtm, release-note-none, cncf-cla: yes, approved

#82 Add more debugging tips to the documentation
  docs/csi-debug.md
Labels: size/M, lgtm, release-note-none, cncf-cla: yes, approved

#83 code cleanup and formatting corrections in iscsi package.
  pkg/iscsi/driver.go
  pkg/iscsi/identityserver.go
  pkg/iscsi/iscsi.go
  pkg/iscsi/iscsi_util.go
  pkg/iscsi/nodeserver.go
  pkg/lib/iscsi/iscsi/iscsi.go
  vendor/github.com/kubernetes-csi/csi-lib-iscsi/iscsi/iscsi.go
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved
